export type PlayerMatchSummaryDTO = {
  status: string;
  gameDuration: number;
  spell1Id: number;
  spell2Id: number;
  victory: boolean;
  championId: number;
  kills: number;
  deaths: number;
  assists: number;
  item0: number;
  item1: number;
  item2: number;
  item3: number;
  item4: number;
  item5: number;
  item6: number;
  perkSubStyle: number;
  perkPrimaryStyle: number;
  totalMinionsKilled: number;
};
